### PR TITLE
[BUG] We also need to intercept 

### PR DESCRIPTION
**Pull request by thomashohn**
method updateRefIndexTable in ReferenceIndex and store that in the queue too since this is the most evil method :-)

### CODE REVIEW

**Comment by NamelessCoder** [comment]
I'll take this and run with it, and at the same time clean up some of the code duplication. Some general notes though:

* The `tstamp` column should not be necessary since not having any sorting should cause FIFO - correct me if I'm wrong!
* The overridden method on ReferenceIndex in the real implementation returns an array of reference information, in the override returns null. Is this safe during record operations - does it prevent recursive processing, for example?
* I may rework the queue update triggering so it is done only once and uses one storage, since ReferenceIndex is used with fresh instances a lot more frequently than DataHandler and probably shouldn't clean queue / save new queue entry every time (at least, would perform better if done with one update).

**Comment by thomashohn** [comment]
- I guess there is no guarantee - that your select will return the records in a FIFO maner - and hence the `tsstamp` column at least ensures that the records will be returned in that order - at least when you copy large amounts of data this could be an issue especially when other reference tables are also involved - it would be nice if they are processes at the "correct" point in time.

- Point 2 to be investigated - but what to return otherwise - the big problem is then still the triggering of readMM. Alternative once should cache the calls to `readMM` - but again that would require at splitting of the `readMM` method into 2 components.

- In the case of large data amounts I think we need to see of we have a performance issue

Looking forward to testing the new versions ;-)

**Comment by NamelessCoder** [comment]
If you come up with something regarding point 2, let me know. I'll start with returning an empty array so at least the data type matches.

**Comment by thomashohn** [comment]
Point 2 would require a change to the core method - but when you have a new version - I could make an alternative version that would use a caching mechanism - but again here the problem would be to decide when to discard the cache and re-cache results 🎱

**Comment by NamelessCoder** [comment]
47% reduction in wall time with this additional override (on master). I'm pushing an update now which does this a little differently, and will skip the timestamp implementation for now (since the value will be the same for many rows, on my setup ~15 records are generated each second).

**Comment by NamelessCoder** [comment]
Replaced by https://github.com/NamelessCoder/asynchronous_reference_indexing/commit/e868bdfb5395d8d5af60a87aaf31e00347277863

**Comment by thomashohn** [comment]
Regarding point 2 - I'm not really sure that the result is really used for any purpose - besides what the side effects are in the arrays that are filled in the method. I'll look further into it tomorrow :-)

**Comment by NamelessCoder** [comment]
I ran some tests and it doesn't seem to break anything if returning an empty array. If it affects anything I'd say it is exactly in the readMM function when it gets called outside of ReferenceIndex itself, since we suppress any recursive calling from within ReferenceIndex.

**Comment by thomashohn** [comment]
I looked shortly into the calls - it seems that it could only affect the reIndexing from the cli interface - I'll look into it further tomorrow with the newest changes - but it really seems to kick ass already ;-)   I had a strange error when copying a really big tree but that might be something else - will keep you informed ;-)

**Pull request closed without merging**
